---

- name: Revert config to backup
  become: true
  ansible.windows.win_copy:
    src: '{{ sysmon_configfile_update.backup_file }}'
    dest: '{{ sysmon_config_file }}'
    backup: false
    remote_src: true
  register: sysmon_configfile_revert

- name: Remove config backup
  ansible.windows.win_file:
    path: '{{ sysmon_configfile_update.backup_file }}'
    state: absent
